"""Add transit, journey, CSV import, FTS5, and RTree schema."""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.search import ensure_search_indexes

revision: str = "20260820_0002"
down_revision: str | Sequence[str] | None = "20260820_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(length=120), nullable=False),
        sa.Column("source_version", sa.String(length=120), nullable=False),
        sa.Column("captured_at", sa.String(length=40), nullable=True),
        sa.Column("license", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("importer_schema_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('staging', 'checking', 'ready', 'failed', "
            "'cancelled', 'retired')",
            name="ck_dataset_version_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name", "source_version", "checksum"),
    )
    op.create_table(
        "import_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=260), nullable=False),
        sa.Column("encoding", sa.String(length=20), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("resolved_rows", sa.Integer(), nullable=False),
        sa.Column("review_rows", sa.Integer(), nullable=False),
        sa.Column("failed_rows", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('parsing', 'ready_for_review', 'committing', "
            "'committed', 'failed', 'cancelled')",
            name="ck_import_batch_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journey_code", sa.String(length=120), nullable=False),
        sa.Column("traveled_at", sa.Date(), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('manual', 'map', 'csv')", name="ck_journey_source"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("journey_code"),
    )
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_version_id", sa.Integer(), nullable=False),
        sa.Column("source_city_code", sa.String(length=100), nullable=False),
        sa.Column("name_cn", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("center_lon", sa.Float(), nullable=False),
        sa.Column("center_lat", sa.Float(), nullable=False),
        sa.Column("min_lon", sa.Float(), nullable=False),
        sa.Column("min_lat", sa.Float(), nullable=False),
        sa.Column("max_lon", sa.Float(), nullable=False),
        sa.Column("max_lat", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('checking', 'ready', 'blocked')", name="ck_city_status"
        ),
        sa.CheckConstraint("center_lat BETWEEN -90 AND 90", name="ck_city_lat"),
        sa.CheckConstraint("center_lon BETWEEN -180 AND 180", name="ck_city_lon"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_version_id", "source_city_code"),
    )
    op.create_index(
        op.f("ix_city_dataset_version_id"), "city", ["dataset_version_id"], unique=False
    )
    op.create_index(op.f("ix_city_name_cn"), "city", ["name_cn"], unique=False)
    op.create_table(
        "line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("name_cn", sa.String(length=160), nullable=False),
        sa.Column("name_en", sa.String(length=240), nullable=True),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("display_color", sa.String(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('checking', 'ready', 'blocked')", name="ck_line_status"
        ),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_id", "normalized_name"),
    )
    op.create_index(op.f("ix_line_city_id"), "line", ["city_id"], unique=False)
    op.create_table(
        "station",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("name_cn", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=300), nullable=True),
        sa.Column("normalized_name", sa.String(length=240), nullable=False),
        sa.Column("pinyin_full", sa.String(length=400), nullable=True),
        sa.Column("pinyin_initials", sa.String(length=120), nullable=True),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("cluster_no", sa.Integer(), nullable=False),
        sa.CheckConstraint("lat BETWEEN -90 AND 90", name="ck_station_lat"),
        sa.CheckConstraint("lon BETWEEN -180 AND 180", name="ck_station_lon"),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_id", "normalized_name", "cluster_no"),
    )
    op.create_index(op.f("ix_station_city_id"), "station", ["city_id"], unique=False)
    op.create_index(
        "ix_station_city_name", "station", ["city_id", "normalized_name"], unique=False
    )
    op.create_index(
        op.f("ix_station_pinyin_full"), "station", ["pinyin_full"], unique=False
    )
    op.create_index(
        op.f("ix_station_pinyin_initials"), "station", ["pinyin_initials"], unique=False
    )
    op.create_table(
        "import_row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column("normalized_json", sa.JSON(), nullable=False),
        sa.Column("resolution_status", sa.String(length=30), nullable=False),
        sa.Column("matched_city_id", sa.Integer(), nullable=True),
        sa.Column("matched_line_id", sa.Integer(), nullable=True),
        sa.Column("matched_start_station_id", sa.Integer(), nullable=True),
        sa.Column("matched_end_station_id", sa.Integer(), nullable=True),
        sa.Column("selected_candidate_id", sa.String(length=160), nullable=True),
        sa.Column("candidate_json", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "resolution_status IN ('resolved', 'needs_review', 'unresolved', "
            "'ignored', 'committed')",
            name="ck_import_row_resolution",
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["matched_city_id"],
            ["city.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_end_station_id"],
            ["station.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_line_id"],
            ["line.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_start_station_id"],
            ["station.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "row_no"),
    )
    op.create_index(
        op.f("ix_import_row_batch_id"), "import_row", ["batch_id"], unique=False
    )
    op.create_table(
        "route_variant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("dataset_version_id", sa.Integer(), nullable=False),
        sa.Column("source_route_id", sa.String(length=240), nullable=False),
        sa.Column("source_route_name", sa.String(length=300), nullable=True),
        sa.Column("direction_name", sa.String(length=160), nullable=True),
        sa.Column("is_loop", sa.Boolean(), nullable=False),
        sa.Column("is_branch", sa.Boolean(), nullable=False),
        sa.Column("geometry_wkb", sa.LargeBinary(), nullable=False),
        sa.Column("match_method", sa.String(length=80), nullable=False),
        sa.Column("quality_status", sa.String(length=20), nullable=False),
        sa.Column("quality_flags_json", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "quality_status IN ('checking', 'ready', 'blocked')",
            name="ck_route_variant_quality",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_version.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["line_id"], ["line.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_version_id", "source_route_id"),
    )
    op.create_index(
        op.f("ix_route_variant_dataset_version_id"),
        "route_variant",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_variant_line_id"), "route_variant", ["line_id"], unique=False
    )
    op.create_table(
        "station_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=300), nullable=False),
        sa.Column("normalized_alias", sa.String(length=340), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["station_id"], ["station.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("station_id", "normalized_alias", "language"),
    )
    op.create_index(
        op.f("ix_station_alias_normalized_alias"),
        "station_alias",
        ["normalized_alias"],
        unique=False,
    )
    op.create_index(
        op.f("ix_station_alias_station_id"),
        "station_alias",
        ["station_id"],
        unique=False,
    )
    op.create_table(
        "journey_leg",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journey_id", sa.Integer(), nullable=False),
        sa.Column("leg_no", sa.Integer(), nullable=False),
        sa.Column("dataset_version_id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("route_variant_id", sa.Integer(), nullable=False),
        sa.Column("start_station_id", sa.Integer(), nullable=False),
        sa.Column("end_station_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=120), nullable=True),
        sa.Column("resolution_status", sa.String(length=30), nullable=False),
        sa.Column("resolution_message", sa.Text(), nullable=True),
        sa.Column("candidate_digest", sa.String(length=100), nullable=False),
        sa.CheckConstraint(
            "resolution_status IN ('resolved', 'needs_review', 'invalidated')",
            name="ck_journey_leg_resolution",
        ),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_version.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["end_station_id"], ["station.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["journey_id"], ["journey.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["line_id"], ["line.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["route_variant_id"], ["route_variant.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["start_station_id"], ["station.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("journey_id", "leg_no"),
    )
    op.create_index(
        op.f("ix_journey_leg_journey_id"), "journey_leg", ["journey_id"], unique=False
    )
    op.create_table(
        "route_stop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_variant_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("source_stop_id", sa.String(length=240), nullable=False),
        sa.Column("source_sequence", sa.Integer(), nullable=False),
        sa.Column("source_lon", sa.Float(), nullable=False),
        sa.Column("source_lat", sa.Float(), nullable=False),
        sa.Column("projected_measure_m", sa.Float(), nullable=False),
        sa.Column("projection_error_m", sa.Float(), nullable=False),
        sa.Column("match_quality", sa.String(length=40), nullable=False),
        sa.CheckConstraint("source_lat BETWEEN -90 AND 90", name="ck_route_stop_lat"),
        sa.CheckConstraint("source_lon BETWEEN -180 AND 180", name="ck_route_stop_lon"),
        sa.ForeignKeyConstraint(
            ["route_variant_id"], ["route_variant.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["station_id"], ["station.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_variant_id", "source_sequence"),
        sa.UniqueConstraint("route_variant_id", "source_stop_id"),
    )
    op.create_index(
        op.f("ix_route_stop_route_variant_id"),
        "route_stop",
        ["route_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_stop_station_id"), "route_stop", ["station_id"], unique=False
    )
    op.create_table(
        "route_edge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_variant_id", sa.Integer(), nullable=False),
        sa.Column("from_route_stop_id", sa.Integer(), nullable=False),
        sa.Column("to_route_stop_id", sa.Integer(), nullable=False),
        sa.Column("from_station_id", sa.Integer(), nullable=False),
        sa.Column("to_station_id", sa.Integer(), nullable=False),
        sa.Column("sequence_from", sa.Integer(), nullable=False),
        sa.Column("sequence_to", sa.Integer(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("geometry_wkb", sa.LargeBinary(), nullable=False),
        sa.Column("min_lon", sa.Float(), nullable=False),
        sa.Column("min_lat", sa.Float(), nullable=False),
        sa.Column("max_lon", sa.Float(), nullable=False),
        sa.Column("max_lat", sa.Float(), nullable=False),
        sa.Column("quality_status", sa.String(length=20), nullable=False),
        sa.Column("quality_flags_json", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "quality_status IN ('checking', 'ready', 'blocked')",
            name="ck_route_edge_quality",
        ),
        sa.CheckConstraint("distance_m > 0", name="ck_route_edge_distance"),
        sa.ForeignKeyConstraint(
            ["from_route_stop_id"], ["route_stop.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["from_station_id"], ["station.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["route_variant_id"], ["route_variant.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_route_stop_id"], ["route_stop.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["to_station_id"], ["station.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_variant_id", "sequence_from", "sequence_to"),
    )
    op.create_index(
        "ix_route_edge_bbox",
        "route_edge",
        ["min_lon", "min_lat", "max_lon", "max_lat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_edge_from_station_id"),
        "route_edge",
        ["from_station_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_edge_route_variant_id"),
        "route_edge",
        ["route_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_edge_to_station_id"),
        "route_edge",
        ["to_station_id"],
        unique=False,
    )
    op.create_table(
        "journey_leg_edge",
        sa.Column("journey_leg_id", sa.Integer(), nullable=False),
        sa.Column("route_edge_id", sa.Integer(), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("reversed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journey_leg_id"], ["journey_leg.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["route_edge_id"], ["route_edge.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("journey_leg_id", "route_edge_id"),
        sa.UniqueConstraint("journey_leg_id", "order_no"),
        sa.UniqueConstraint("journey_leg_id", "route_edge_id", "order_no"),
    )
    ensure_search_indexes(op.get_bind())


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        for trigger in (
            "route_edge_spatial_delete",
            "route_edge_spatial_update",
            "route_edge_spatial_insert",
            "station_spatial_delete",
            "station_spatial_update",
            "station_spatial_insert",
            "station_alias_fts_delete",
            "station_alias_fts_update",
            "station_alias_fts_insert",
            "station_fts_delete",
            "station_fts_update",
            "station_fts_insert",
        ):
            op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
        op.execute("DROP TABLE IF EXISTS route_edge_spatial")
        op.execute("DROP TABLE IF EXISTS station_spatial")
        op.execute("DROP TABLE IF EXISTS station_fts")
    op.drop_table("journey_leg_edge")
    op.drop_index(op.f("ix_route_edge_to_station_id"), table_name="route_edge")
    op.drop_index(op.f("ix_route_edge_route_variant_id"), table_name="route_edge")
    op.drop_index(op.f("ix_route_edge_from_station_id"), table_name="route_edge")
    op.drop_index("ix_route_edge_bbox", table_name="route_edge")
    op.drop_table("route_edge")
    op.drop_index(op.f("ix_route_stop_station_id"), table_name="route_stop")
    op.drop_index(op.f("ix_route_stop_route_variant_id"), table_name="route_stop")
    op.drop_table("route_stop")
    op.drop_index(op.f("ix_journey_leg_journey_id"), table_name="journey_leg")
    op.drop_table("journey_leg")
    op.drop_index(op.f("ix_station_alias_station_id"), table_name="station_alias")
    op.drop_index(op.f("ix_station_alias_normalized_alias"), table_name="station_alias")
    op.drop_table("station_alias")
    op.drop_index(op.f("ix_route_variant_line_id"), table_name="route_variant")
    op.drop_index(
        op.f("ix_route_variant_dataset_version_id"), table_name="route_variant"
    )
    op.drop_table("route_variant")
    op.drop_index(op.f("ix_import_row_batch_id"), table_name="import_row")
    op.drop_table("import_row")
    op.drop_index(op.f("ix_station_pinyin_initials"), table_name="station")
    op.drop_index(op.f("ix_station_pinyin_full"), table_name="station")
    op.drop_index("ix_station_city_name", table_name="station")
    op.drop_index(op.f("ix_station_city_id"), table_name="station")
    op.drop_table("station")
    op.drop_index(op.f("ix_line_city_id"), table_name="line")
    op.drop_table("line")
    op.drop_index(op.f("ix_city_name_cn"), table_name="city")
    op.drop_index(op.f("ix_city_dataset_version_id"), table_name="city")
    op.drop_table("city")
    op.drop_table("journey")
    op.drop_table("import_batch")
    op.drop_table("dataset_version")
